#!/bin/bash
set -euo pipefail
./install-dependencies.sh

#(

# looks like explicit clean is necessary, otherwise jacoco does not fail on too little coverage
mvn clean

#rm -rf target/site/jacoco
echo "Normal test run..."
echo "Report will be in ./target/site/jacoco/index.html"
mvn test jacoco:report@report jacoco:check@check
echo "Coverage goal met, see report:"
ls -l target/site/jacoco/index.html

#) |& tee test.log
